---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab
  namespace: openhab
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2G
