---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhab
  namespace: openhab
  labels:
    app: openhab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhab
  template:
    metadata:
      labels:
        app: openhab
    spec:
      # to allow bluetooth access
      # hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet

      volumes:
      - name: openhab
        persistentVolumeClaim:
          claimName: openhab
      - name: zstick
        hostPath:
          path: /dev/ttyUSB0

      initContainers:
      - name: init-openhab
        image: busybox:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          while [ ! $(ls /final_configs | wc -l) -gt 0 ]; do
            echo 'no configs found; waiting 5s'
            sleep 5
          done
          echo 'configs found; starting'
        volumeMounts:
        - name: openhab
          mountPath: /final_configs
          subPath: conf
          readOnly: true

      containers:
      - name: openhab
        # image: openhab/openhab:2.5.10
        image: openhab/openhab:3.0.1
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true # to allow bluetooth and zstick access, might be able to be scoped down some
        volumeMounts:
        - name: zstick
          mountPath: /dev/ttyUSB0
        - name: openhab
          mountPath: /openhab/conf
          subPath: conf
        - name: openhab
          mountPath: /openhab/userdata
          subPath: userdata
