---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openhab-config
  namespace: openhab
data:
  config.yaml: |
    groups:
      house:
        name: House
      floor_ground:
        name: Floor_Ground
      floor_first:
        name: Floor_First
      floor_second:
        name: Floor_Second
      room_bedroom_main:
        name: Room_Bedroom_main
    things:
      airquality:
        station_id: 86
      daikin:
        great_room:
          host: great-room.hvac.home.lan
          label: HVAC
          location: Great Room
          thing_id: great_room
        main_bedroom:
          host: main-bedroom.hvac.home.lan
          label: HVAC
          location: Main Bedroom
          thing_id: main_bedroom
      zwave:
        controller:
          port: /dev/ttyUSB0
        sensors:
          front_door:
            label: Door Sensor
            location: Entryway
            node_id: 2
            thing_id: front_door_sensor
            type_id: eco_dwzwave25_00_000
          garage_door:
            label: Tilt Sensor
            location: Garage
            node_id: 3
            thing_id: garage_tilt_sensor
            type_id: eco_tiltzwave25_00_000
    settings:
      addons:
        package: minimal
        binding: airquality,bluetooth,daikin,network,systeminfo,telegram,zwave
        persistence: influxdb
        ui: basic,habmin,paper,restdocs
      ephemeris:
        country: us
        region: or
        dayset:
          trash: Friday
      persistence:
        influxdb:
          db: openhab
          url: http://influxdb:8086
      i18n:
        language: en
        region: US
        timezone: US/Pacific
        measurement_system: US
