---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhab-deployment
  namespace: openhab
  labels:
    app: openhab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhab
  template:
    metadata:
      labels:
        app: openhab
    spec:
      # to allow bluetooth access
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      volumes:
      - name: openhab-conf
        persistentVolumeClaim:
          claimName: openhab-conf-pvc
      - name: openhab-userdata
        persistentVolumeClaim:
          claimName: openhab-userdata-pvc
      - name: openhab-conf-repo
        persistentVolumeClaim:
          claimName: openhab-conf-repo-pvc
      - name: zstick
        hostPath:
          path: /dev/ttyUSB0

      initContainers:
      - name: init-openhab
        image: busybox:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          while [ ! $(ls /final_configs | wc -l) -gt 0 ]; do
            echo 'no configs found; waiting 5s'
            sleep 5
          done
          echo 'configs found; starting'
        volumeMounts:
        - name: openhab-conf
          mountPath: /final_configs
          readOnly: true

      containers:
      - name: openhab
        image: jgoodhouse/openhab:2.5.9-78406f6
        imagePullPolicy: Always
        securityContext:
          privileged: true # to allow bluetooth and zstick access, might be able to be scoped down some
        volumeMounts:
        - name: zstick
          mountPath: /dev/ttyUSB0
        - name: openhab-conf
          mountPath: /openhab/conf
        - name: openhab-userdata
          mountPath: /openhab/userdata
